### ISSUE TITLE
出现二个bug

### ISSUE THREAD

**Issue by dfaofeng** [mamoe/mirai-console-intellij#10]
第一个是生成java代码的
![QQ截图20200412013828](https://user-images.githubusercontent.com/14891398/79050728-8d713c80-7c5e-11ea-9cba-0e7ee7ae713c.png)
![QQ截图20200412013857](https://user-images.githubusercontent.com/14891398/79050731-8ea26980-7c5e-11ea-950e-8699cd30950e.png)
![QQ截图20200412013907](https://user-images.githubusercontent.com/14891398/79050732-8f3b0000-7c5e-11ea-9b2b-b44143509b87.png)
![QQ截图20200412013924](https://user-images.githubusercontent.com/14891398/79050733-906c2d00-7c5e-11ea-9289-4dbb36a3923c.png)
第二个是生成kotlin代码的
都是生成kotlin代码默认值
![QQ截图20200412014132](https://user-images.githubusercontent.com/14891398/79050777-daeda980-7c5e-11ea-85ef-961c8ef35584.png)

都是导入gradel时出错的

**Comment by Him188** [comment]
使用更高版本（9+） JDK 可以解决。

**Comment by Him188** [comment]
#7
