### ISSUE TITLE
idea安装提示不兼容,插件市场搜索不到

### ISSUE THREAD

**Issue by kcwxzqby** [mamoe/mirai-console-intellij#14]
如题,我的idea版本是2019.2
![111](https://user-images.githubusercontent.com/56684215/82126386-fc523000-97de-11ea-8c42-8865ed512407.jpg)
![222](https://user-images.githubusercontent.com/56684215/82126387-feb48a00-97de-11ea-9547-978b5677d79d.jpg)

**Comment by Him188** [comment]
暂时需要2019.3，推荐2020.1
目前主要开发目标为 mirai-console 重构，之后才会继续维护IJ插件

**Comment by optimize-2** [comment]
2020.1.1，也是idea安装提示不兼容,插件市场搜索不到

**Comment by yunzimo** [comment]
惨了，更新了一下不能用了
![image](https://user-images.githubusercontent.com/45143713/88801084-b866a880-d1db-11ea-9e0c-9043546a272f.png)

**Comment by Him188** [comment]
console 正在重构，插件暂不更新
