### ISSUE TITLE
idea导入插件失败

### ISSUE THREAD

**Issue by Sincky** [mamoe/mirai-console-intellij#3]
![image](https://user-images.githubusercontent.com/30948192/77051168-d807ec00-6a05-11ea-8615-b8671745aa98.png)

Plugin 'Mirai Console' is incompatible with this installation

idea版本：2019.2 community edition

![image](https://user-images.githubusercontent.com/30948192/77051045-a55df380-6a05-11ea-82b6-d291993bda5f.png)

**Comment by Sincky** [comment]
更新版本到2019.3解决了

**Comment by Him188** [comment]
将会降低版本需求

**Comment by liujiahua123123** [comment]
fix soon

**Comment by liujiahua123123** [comment]
fixed
